Update e2e-tests.yml

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -187,7 +187,7 @@ jobs:
           npx playwright test ${{ env.TEST_PATH }} --project=${{ matrix.browser }} --workers=1
           echo "PLAYWRIGHT_EXIT_CODE=$?" >> $GITHUB_OUTPUT
         # テストが失敗してもワークフローを中断せず、後続のステップ（アーティファクトのアップロードなど）を実行する
-        continue-on-error: true
+        # continue-on-error: true
         env:
           # DEBUG: pw:api
           TEST_RUN_SUFFIX: ${{ env.OS_SHORT_NAME }} 
@@ -272,3 +272,10 @@ jobs:
           PWAPPY_TEST_AUTH: ${{ secrets.PWAPPY_TEST_AUTH }}
           PWAPPY_TEST_IDENT_KEY: ${{ secrets.PWAPPY_TEST_IDENT_KEY }}
           PWAPPY_LOGIN: ${{ secrets.PWAPPY_LOGIN }}
+
+      - name: Check upstream job status
+        # 先行するe2e-testジョブの結果が 'failure' だったら
+        if: needs.e2e-test.result == 'failure'
+        run: |
+          echo "Upstream e2e-test job failed. Propagating failure status."
+          exit 1 # このジョブを失敗させる
